"""Add fiel is Calulated to Theroric Params

Revision ID: c948714912dd
Revises: d14e72570c6a
Create Date: 2023-09-24 00:40:40.148472

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c948714912dd'
down_revision = 'd14e72570c6a'
branch_labels = None
depends_on = None


def upgrade() -> None:
  # Agregar la columna con un valor predeterminado no nulo
  op.add_column('theoric_params', sa.Column(
      'isCalculated', sa.Boolean(), nullable=True, default=False))


def downgrade() -> None:
  # ### commands auto generated by Alembic - please adjust! ###
  op.drop_column('theoric_params', 'isCalculated')
  # ### end Alembic commands ###
