"""Last changes

Revision ID: d14e72570c6a
Revises: e8d5ca6f13c1
Create Date: 2023-09-23 18:27:06.141537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd14e72570c6a'
down_revision = 'e8d5ca6f13c1'
branch_labels = None
depends_on = None


def upgrade() -> None:
  # ### commands auto generated by Alembic - please adjust! ###
  op.drop_table('theoric_study')
  op.alter_column('users', 'token',
                  existing_type=sa.VARCHAR(length=35),
                  nullable=False)
  op.alter_column('users', 'first_name',
                  existing_type=sa.VARCHAR(length=50),
                  nullable=True)
  op.alter_column('users', 'last_name',
                  existing_type=sa.VARCHAR(length=50),
                  nullable=True)
  op.create_foreign_key(None, 'weather', 'locations', ['location_id'], ['id'])
  # ### end Alembic commands ###


def downgrade() -> None:
  # ### commands auto generated by Alembic - please adjust! ###
  op.drop_constraint(None, 'weather', type_='foreignkey')
  op.alter_column('users', 'last_name',
                  existing_type=sa.VARCHAR(length=50),
                  nullable=False)
  op.alter_column('users', 'first_name',
                  existing_type=sa.VARCHAR(length=50),
                  nullable=False)
  op.alter_column('users', 'token',
                  existing_type=sa.VARCHAR(length=35),
                  nullable=True)
  op.create_table('theoric_study',
                  sa.Column('id', sa.INTEGER(),
                            autoincrement=True, nullable=False),
                  sa.Column('inclination_deg', sa.DOUBLE_PRECISION(
                      precision=53), autoincrement=False, nullable=True),
                  sa.Column('azimuth_deg', sa.DOUBLE_PRECISION(
                      precision=53), autoincrement=False, nullable=True),
                  sa.Column('granularity', sa.INTEGER(),
                            autoincrement=False, nullable=True),
                  sa.Column('pipeline_separation', sa.DOUBLE_PRECISION(
                      precision=53), autoincrement=False, nullable=True),
                  sa.Column('location_id', sa.INTEGER(),
                            autoincrement=False, nullable=True),
                  sa.Column('pipeline_id', sa.INTEGER(),
                            autoincrement=False, nullable=True),
                  sa.ForeignKeyConstraint(
                      ['location_id'], ['locations.id'], name='theoric_study_location_id_fkey'),
                  sa.ForeignKeyConstraint(
                      ['pipeline_id'], ['pipelines.id'], name='theoric_study_pipeline_id_fkey'),
                  sa.PrimaryKeyConstraint('id', name='theoric_study_pkey')
                  )
  # ### end Alembic commands ###
